// priv/nb_inertia/vue/modals/HeadlessModal.vue
<template>
  <slot v-if="isOpen && modalId" :modal="currentModal" :close="close" />
</template>

<script setup lang="ts">
import { ref, watch, onUnmounted, computed } from 'vue';
import { router } from '../router';
import { useModalStack } from './modalStack';
import type { ModalConfig } from './types';
import type { Component } from 'vue';

/**
 * HeadlessModal - Core modal state management for Vue
 *
 * Provides foundational modal logic without any UI:
 * - Modal stack integration
 * - Event system (close, success, blur, focus, beforeClose)
 * - Lifecycle management
 * - Keyboard handling (ESC to close)
 *
 * Use this as a base for building styled modal components.
 *
 * @example
 * ```vue
 * <template>
 *   <HeadlessModal
 *     :component="UserProfile"
 *     :component-props="{ userId: 1 }"
 *     :config="{ size: 'lg' }"
 *     base-url="/users"
 *     :open="true"
 *     @close="handleClose"
 *   >
 *     <template #default="{ modal, close }">
 *       <component :is="modal.component" v-bind="modal.props" :close="close" />
 *     </template>
 *   </HeadlessModal>
 * </template>
 * ```
 */

interface Props {
  /**
   * Unique identifier for this modal
   */
  id?: string;

  /**
   * Modal component to render
   */
  component: Component;

  /**
   * Props to pass to the modal component
   */
  componentProps?: Record<string, any>;

  /**
   * Modal configuration
   */
  config?: ModalConfig;

  /**
   * Base URL for the modal (used for navigation)
   */
  baseUrl: string;

  /**
   * Whether the modal is currently open
   */
  open?: boolean;
}

interface Emits {
  (e: 'close'): void;
  (e: 'success'): void;
}

const props = withDefaults(defineProps<Props>(), {
  componentProps: () => ({}),
  config: () => ({}),
  open: true,
});

const emit = defineEmits<Emits>();

const { pushModal, popModal, emitEvent } = useModalStack();
const modalId = ref<string | null>(props.id || null);
const isClosing = ref(false);
const isOpen = ref(props.open);

// Watch for open prop changes
watch(() => props.open, (newVal) => {
  isOpen.value = newVal;
});

// Current modal data
const currentModal = computed(() => {
  if (!modalId.value) return null;
  return {
    id: modalId.value,
    component: props.component,
    props: props.componentProps,
    config: props.config,
    baseUrl: props.baseUrl,
    index: 0,
    eventHandlers: new Map(),
  };
});

// Register modal in stack when opened
watch(isOpen, (newVal) => {
  if (newVal && !modalId.value) {
    const newId = pushModal({
      component: props.component,
      props: props.componentProps,
      config: props.config,
      baseUrl: props.baseUrl,
    });
    modalId.value = newId;
  }
});

// Close modal function
async function close(success = false) {
  if (!modalId.value || isClosing.value) return;

  isClosing.value = true;

  // Emit beforeClose event - can be canceled
  const shouldClose = await emitEvent(modalId.value, 'beforeClose');
  if (!shouldClose) {
    isClosing.value = false;
    return;
  }

  // Emit close or success event
  await emitEvent(modalId.value, success ? 'success' : 'close');

  // Remove from stack
  popModal(modalId.value);

  // Call emit callbacks
  if (success) {
    emit('success');
  } else {
    emit('close');
  }

  // Navigate to base URL
  if (props.baseUrl) {
    router.visit(props.baseUrl);
  }

  modalId.value = null;
  isClosing.value = false;
  isOpen.value = false;
}

// Handle ESC key
function handleEscape(e: KeyboardEvent) {
  if (!isOpen.value || !modalId.value || props.config?.closeExplicitly) return;

  if (e.key === 'Escape') {
    e.preventDefault();
    close();
  }
}

// Setup keyboard listener
watch(isOpen, (newVal) => {
  if (newVal && !props.config?.closeExplicitly) {
    document.addEventListener('keydown', handleEscape);
  } else {
    document.removeEventListener('keydown', handleEscape);
  }
});

// Cleanup on unmount
onUnmounted(() => {
  document.removeEventListener('keydown', handleEscape);
  if (modalId.value) {
    popModal(modalId.value);
  }
});

// Initialize modal if open on mount
if (isOpen.value && !modalId.value) {
  const newId = pushModal({
    component: props.component,
    props: props.componentProps,
    config: props.config,
    baseUrl: props.baseUrl,
  });
  modalId.value = newId;
}
</script>

// priv/nb_inertia/react/modals/HeadlessModal.tsx
import React, { useEffect, useState, useCallback } from 'react';
import { router } from '../router';
import { useModalStack } from './modalStack';
import type { ModalConfig, ModalInstance } from './types';

export { useModalStack, useModal, ModalStackProvider } from './modalStack';
export type { ModalConfig, ModalInstance, ModalEventType, ModalEventHandler } from './modalStack';

/**
 * Props for HeadlessModal component
 */
export interface HeadlessModalProps {
  /**
   * Unique identifier for this modal
   */
  id?: string;

  /**
   * Modal component to render
   */
  component: React.ComponentType<any>;

  /**
   * Props to pass to the modal component
   */
  componentProps?: Record<string, any>;

  /**
   * Modal configuration
   */
  config?: ModalConfig;

  /**
   * Base URL for the modal (used for navigation)
   */
  baseUrl: string;

  /**
   * Whether the modal is currently open
   */
  open?: boolean;

  /**
   * Callback when the modal is requested to close
   */
  onClose?: () => void;

  /**
   * Callback when the modal successfully closes
   */
  onSuccess?: () => void;

  /**
   * Children to render (for render prop pattern)
   */
  children?: (modal: ModalInstance, close: () => void) => React.ReactNode;
}

/**
 * HeadlessModal - Core modal state management
 *
 * This component provides the foundational modal logic without any UI:
 * - Modal stack integration
 * - Event system (close, success, blur, focus, beforeClose)
 * - Lifecycle management
 * - Keyboard handling (ESC to close)
 * - Focus trap
 *
 * Use this as a base for building styled modal components.
 */
export const HeadlessModal: React.FC<HeadlessModalProps> = ({
  id,
  component: Component,
  componentProps = {},
  config = {},
  baseUrl,
  open = true,
  onClose,
  onSuccess,
  children,
}) => {
  const { pushModal, popModal, emitEvent } = useModalStack();
  const [modalId, setModalId] = useState<string | null>(id || null);
  const [isClosing, setIsClosing] = useState(false);

  // Register modal in stack when opened
  useEffect(() => {
    if (open && !modalId) {
      const newId = pushModal({
        component: Component,
        props: componentProps,
        config,
        baseUrl,
      });
      setModalId(newId);
    }
  }, [open, modalId, pushModal, Component, componentProps, config, baseUrl]);

  // Close modal function
  const close = useCallback(async (success = false) => {
    if (!modalId || isClosing) return;

    setIsClosing(true);

    // Emit beforeClose event - can be canceled
    const shouldClose = await emitEvent(modalId, 'beforeClose');
    if (!shouldClose) {
      setIsClosing(false);
      return;
    }

    // Emit close or success event
    await emitEvent(modalId, success ? 'success' : 'close');

    // Remove from stack
    popModal(modalId);

    // Call callbacks
    if (success && onSuccess) {
      onSuccess();
    } else if (!success && onClose) {
      onClose();
    }

    // Navigate to base URL
    if (baseUrl) {
      router.visit(baseUrl);
    }

    setModalId(null);
    setIsClosing(false);
  }, [modalId, isClosing, emitEvent, popModal, onSuccess, onClose, baseUrl]);

  // Handle ESC key
  useEffect(() => {
    if (!open || !modalId || config.closeExplicitly) return;

    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.preventDefault();
        close();
      }
    };

    document.addEventListener('keydown', handleEscape);
    return () => document.removeEventListener('keydown', handleEscape);
  }, [open, modalId, config.closeExplicitly, close]);

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (modalId) {
        popModal(modalId);
      }
    };
  }, [modalId, popModal]);

  if (!open || !modalId) {
    return null;
  }

  // If children function is provided, use render prop pattern
  if (children && modalId) {
    const modal = {
      id: modalId,
      component: Component,
      props: componentProps,
      config,
      baseUrl,
      index: 0,
      eventHandlers: new Map(),
    };
    return <>{children(modal, close)}</>;
  }

  // Default: render the component
  return <Component {...componentProps} close={close} />;
};

export default HeadlessModal;
